/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.kelompok2.projectmanagement.view;

import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Adam
 */
public class Home extends javax.swing.JPanel {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelName = new javax.swing.JLabel();
        lblFullname = new javax.swing.JLabel();
        txFullname = new javax.swing.JTextField();
        lblFullname1 = new javax.swing.JLabel();
        txUsername = new javax.swing.JTextField();
        lblFullname2 = new javax.swing.JLabel();
        txPosition = new javax.swing.JTextField();
        lblFullname3 = new javax.swing.JLabel();
        txSince = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 0, 0));

        labelName.setFont(new java.awt.Font("Sitka Text", 0, 24)); // NOI18N
        labelName.setForeground(new java.awt.Color(204, 204, 204));
        labelName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelName.setText("jLabel1");

        lblFullname.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        lblFullname.setForeground(new java.awt.Color(204, 204, 204));
        lblFullname.setText("Name");

        txFullname.setEditable(false);
        txFullname.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        txFullname.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txFullname.setText("jTextField1");

        lblFullname1.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        lblFullname1.setForeground(new java.awt.Color(204, 204, 204));
        lblFullname1.setText("Username");

        txUsername.setEditable(false);
        txUsername.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        txUsername.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txUsername.setText("jTextField1");

        lblFullname2.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        lblFullname2.setForeground(new java.awt.Color(204, 204, 204));
        lblFullname2.setText("Position");

        txPosition.setEditable(false);
        txPosition.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        txPosition.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txPosition.setText("jTextField1");

        lblFullname3.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        lblFullname3.setForeground(new java.awt.Color(204, 204, 204));
        lblFullname3.setText("Member since");

        txSince.setEditable(false);
        txSince.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        txSince.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txSince.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFullname2)
                    .addComponent(lblFullname3)
                    .addComponent(lblFullname1)
                    .addComponent(lblFullname))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txFullname)
                    .addComponent(txUsername)
                    .addComponent(txSince)
                    .addComponent(txPosition, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFullname)
                    .addComponent(txFullname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFullname1)
                    .addComponent(txUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFullname2)
                    .addComponent(txPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFullname3)
                    .addComponent(txSince, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setLabelName(String name) {
        labelName.setText(name);
    }

    public void setTxFullname(String name) {
        txFullname.setText(name);
    }

    public void setTxPosition(String position) {
        txPosition.setText(position);
    }

    public void setTxSince(String since) {
        txSince.setText(since);
    }

    public void setTxUsername(String username) {
        txUsername.setText(username);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel lblFullname;
    private javax.swing.JLabel lblFullname1;
    private javax.swing.JLabel lblFullname2;
    private javax.swing.JLabel lblFullname3;
    private javax.swing.JTextField txFullname;
    private javax.swing.JTextField txPosition;
    private javax.swing.JTextField txSince;
    private javax.swing.JTextField txUsername;
    // End of variables declaration//GEN-END:variables
}
