/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.kelompok2.projectmanagement.view;

import id.kelompok2.projectmanagement.view.View;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JRadioButton;

/**
 *
 * @author Iwan Ma'ruf
 */
public class Login extends javax.swing.JFrame implements View {

    /**
     * Creates new form CobaCobaLogin
     */
    public Login() {
        initComponents();
        populateBirthCombo();
    }

    public JButton getBtnLogin() {
        return btnLogin;
    }

    public JButton getBtnSignUp() {
        return btnSignUp;
    }
    public String getUser(){
        return usernameLogin.getText();
    }
    public String getPass(){
        return passwordLogin.getText();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblTitle = new javax.swing.JLabel();
        lblMotto = new javax.swing.JLabel();
        usernameLogin = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        lblSignUp = new javax.swing.JLabel();
        firstName = new javax.swing.JTextField();
        lastName = new javax.swing.JTextField();
        mailField = new javax.swing.JTextField();
        usernameSignUp = new javax.swing.JTextField();
        passwordLogin = new javax.swing.JPasswordField();
        passwordSignUp = new javax.swing.JPasswordField();
        lblTerms = new javax.swing.JLabel();
        lblPolicy = new javax.swing.JLabel();
        btnSignUp = new javax.swing.JButton();
        radioMale = new javax.swing.JRadioButton();
        radioFemale = new javax.swing.JRadioButton();
        comboMonth = new javax.swing.JComboBox<String>();
        comboYear = new javax.swing.JComboBox<String>();
        comboDay = new javax.swing.JComboBox<String>();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 687));
        setSize(new java.awt.Dimension(1000, 687));
        getContentPane().setLayout(null);

        lblTitle.setFont(new java.awt.Font("Sitka Text", 0, 45)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 153));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("ON-BOARD");
        getContentPane().add(lblTitle);
        lblTitle.setBounds(160, 0, 247, 70);

        lblMotto.setFont(new java.awt.Font("Sitka Text", 0, 24)); // NOI18N
        lblMotto.setForeground(new java.awt.Color(255, 255, 153));
        lblMotto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMotto.setText("Nobody's left behind with ON-BOARD");
        getContentPane().add(lblMotto);
        lblMotto.setBounds(530, 0, 444, 34);

        usernameLogin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usernameLogin.setText("Username");
        usernameLogin.setToolTipText("Username");
        usernameLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameLoginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameLoginFocusLost(evt);
            }
        });
        usernameLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameLoginActionPerformed(evt);
            }
        });
        getContentPane().add(usernameLogin);
        usernameLogin.setBounds(540, 40, 110, 30);

        btnLogin.setText("Log In");
        getContentPane().add(btnLogin);
        btnLogin.setBounds(850, 40, 113, 30);

        lblSignUp.setFont(new java.awt.Font("Sitka Text", 0, 24)); // NOI18N
        lblSignUp.setForeground(new java.awt.Color(255, 255, 153));
        lblSignUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSignUp.setText("OR SIGN UP FOR FREE");
        getContentPane().add(lblSignUp);
        lblSignUp.setBounds(620, 90, 320, 30);

        firstName.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        firstName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        firstName.setText("First name");
        firstName.setToolTipText("First name");
        firstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstNameFocusLost(evt);
            }
        });
        firstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameActionPerformed(evt);
            }
        });
        getContentPane().add(firstName);
        firstName.setBounds(570, 130, 200, 30);

        lastName.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        lastName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lastName.setText("Last name");
        lastName.setToolTipText("Last name");
        lastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastNameFocusLost(evt);
            }
        });
        getContentPane().add(lastName);
        lastName.setBounds(780, 130, 190, 30);

        mailField.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        mailField.setText("Email");
        mailField.setToolTipText("Email");
        mailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mailFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                mailFieldFocusLost(evt);
            }
        });
        getContentPane().add(mailField);
        mailField.setBounds(570, 190, 400, 30);

        usernameSignUp.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        usernameSignUp.setText("Username");
        usernameSignUp.setToolTipText("Desired username");
        usernameSignUp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameSignUpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameSignUpFocusLost(evt);
            }
        });
        getContentPane().add(usernameSignUp);
        usernameSignUp.setBounds(570, 250, 400, 30);

        passwordLogin.setText("Password");
        passwordLogin.setToolTipText("Password");
        passwordLogin.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        passwordLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordLoginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordLoginFocusLost(evt);
            }
        });
        getContentPane().add(passwordLogin);
        passwordLogin.setBounds(701, 40, 100, 30);

        passwordSignUp.setText("Password");
        passwordSignUp.setToolTipText("Desired password");
        passwordSignUp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordSignUpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordSignUpFocusLost(evt);
            }
        });
        getContentPane().add(passwordSignUp);
        passwordSignUp.setBounds(570, 310, 400, 30);

        lblTerms.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        lblTerms.setForeground(new java.awt.Color(255, 255, 255));
        lblTerms.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTerms.setText("By clicking Sign In, you agree to our Terms");
        getContentPane().add(lblTerms);
        lblTerms.setBounds(620, 520, 320, 20);

        lblPolicy.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        lblPolicy.setForeground(new java.awt.Color(255, 255, 255));
        lblPolicy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPolicy.setText(" and that you have read our Data Policy");
        getContentPane().add(lblPolicy);
        lblPolicy.setBounds(640, 540, 280, 30);

        btnSignUp.setFont(new java.awt.Font("Sitka Text", 0, 36)); // NOI18N
        btnSignUp.setText("Sign Up");
        getContentPane().add(btnSignUp);
        btnSignUp.setBounds(680, 570, 210, 70);

        buttonGroup1.add(radioMale);
        radioMale.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        radioMale.setText("Male");
        getContentPane().add(radioMale);
        radioMale.setBounds(650, 460, 67, 31);

        buttonGroup1.add(radioFemale);
        radioFemale.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        radioFemale.setText("Female");
        getContentPane().add(radioFemale);
        radioFemale.setBounds(810, 460, 85, 31);

        comboMonth.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        comboMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMonthActionPerformed(evt);
            }
        });
        getContentPane().add(comboMonth);
        comboMonth.setBounds(690, 380, 140, 30);

        comboYear.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        comboYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboYearActionPerformed(evt);
            }
        });
        getContentPane().add(comboYear);
        comboYear.setBounds(840, 380, 130, 30);

        comboDay.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        comboDay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1" }));
        getContentPane().add(comboDay);
        comboDay.setBounds(570, 380, 110, 30);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/BackgroundLogin.jpg"))); // NOI18N
        background.setMaximumSize(new java.awt.Dimension(1010, 680));
        background.setMinimumSize(new java.awt.Dimension(1010, 680));
        background.setPreferredSize(new java.awt.Dimension(1010, 680));
        getContentPane().add(background);
        background.setBounds(-6, 0, 1010, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameLoginFocusGained
        if(usernameLogin.getText().equals("Username")) usernameLogin.setText("");
    }//GEN-LAST:event_usernameLoginFocusGained

    private void usernameLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameLoginFocusLost
        if(usernameLogin.getText().equals("")) usernameLogin.setText("Username");
    }//GEN-LAST:event_usernameLoginFocusLost

    private void usernameLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameLoginActionPerformed

    private void firstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameActionPerformed

    private void passwordLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordLoginFocusGained
        if(passwordLogin.getText().equals("Password")) passwordLogin.setText("");
    }//GEN-LAST:event_passwordLoginFocusGained

    private void passwordLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordLoginFocusLost
        if(passwordLogin.getText().equals("")) passwordLogin.setText("Password");
    }//GEN-LAST:event_passwordLoginFocusLost

    private void firstNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNameFocusGained
        if(firstName.getText().equals("First name")) firstName.setText("");
    }//GEN-LAST:event_firstNameFocusGained

    private void firstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNameFocusLost
        if(firstName.getText().equals("")) firstName.setText("First name");
    }//GEN-LAST:event_firstNameFocusLost

    private void lastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameFocusGained
        if(lastName.getText().equals("Last name")) lastName.setText("");
    }//GEN-LAST:event_lastNameFocusGained

    private void lastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameFocusLost
        if(lastName.getText().equals("")) lastName.setText("Last name");
    }//GEN-LAST:event_lastNameFocusLost

    private void mailFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mailFieldFocusGained
        if(mailField.getText().equals("Email")) mailField.setText("");
    }//GEN-LAST:event_mailFieldFocusGained

    private void mailFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mailFieldFocusLost
        if(mailField.getText().equals("")) mailField.setText("Email");
    }//GEN-LAST:event_mailFieldFocusLost

    private void usernameSignUpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameSignUpFocusGained
        if(usernameSignUp.getText().equals("Username")) usernameSignUp.setText("");
    }//GEN-LAST:event_usernameSignUpFocusGained

    private void usernameSignUpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameSignUpFocusLost
        if(usernameSignUp.getText().equals("")) usernameSignUp.setText("Username");
    }//GEN-LAST:event_usernameSignUpFocusLost

    private void passwordSignUpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordSignUpFocusGained
        if(passwordSignUp.getText().equals("Password")) passwordSignUp.setText("");
    }//GEN-LAST:event_passwordSignUpFocusGained

    private void passwordSignUpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordSignUpFocusLost
        if(passwordSignUp.getText().equals("")) passwordSignUp.setText("Password");
    }//GEN-LAST:event_passwordSignUpFocusLost

    private void comboMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMonthActionPerformed
        populateComboDay();
    }//GEN-LAST:event_comboMonthActionPerformed

    private void comboYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboYearActionPerformed
        populateComboDay();
    }//GEN-LAST:event_comboYearActionPerformed

    private void populateBirthCombo() {
        List<String> year = new ArrayList<>();
        for(int i = 1901; i < 2017; i++) {
            year.add(String.valueOf(i));
        }
        comboYear.setModel(new DefaultComboBoxModel(year.toArray()));
        List<String> month = new ArrayList<>();
        month.add("January");
        month.add("February");
        month.add("March");
        month.add("April");
        month.add("May");
        month.add("June");
        month.add("July");
        month.add("August");
        month.add("September");
        month.add("October");
        month.add("November");
        month.add("December");
        comboMonth.setModel(new DefaultComboBoxModel(month.toArray()));
        
        populateComboDay();
    }
    
    private void populateComboDay() {
        List<Integer> day = new ArrayList<>();
        switch(comboMonth.getSelectedItem().toString()) {
            case "January":
            case "March":
            case "May":
            case "July":
            case "August":
            case "October":
            case "December":
                day.clear();
                for(int i = 1; i < 32; i++) {
                    day.add(i);
                }
                comboDay.setModel(new DefaultComboBoxModel(day.toArray()));
                break;
            case "February":
                int year = Integer.parseInt(comboYear.getSelectedItem().toString());
                if((year % 4 == 0 && year % 100 != 0) || year % 400 == 0) { // leap
                    day.clear();
                    for(int i = 1; i < 30; i++) {
                        day.add(i);
                    }
                    comboDay.setModel(new DefaultComboBoxModel(day.toArray()));
                }
                break;
            case "April":
            case "June":
            case "September":
            case "November":
                day.clear();
                for(int i = 1; i < 31; i++) {
                    day.add(i);
                }
                comboDay.setModel(new DefaultComboBoxModel(day.toArray()));
                break;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login window = new Login();
                window.setVisible(true);
                window.setSize(new java.awt.Dimension(1000, 687));
                window.setLocationRelativeTo(null);
                window.setTitle("ON-BOARD");
            }
        });
    }

    public String getFirstName() {
        return firstName.getText();
    }
    
    public String getLastName() {
        return lastName.getText();
    }
    
    public String getEmail() {
        return mailField.getText();
    }
    
    public String getUserSignup() {
        return usernameSignUp.getText();
    }
    
    public String getPassSignup() {
        return passwordSignUp.getText();
    }
    
    public java.sql.Date getBirthDate() {
        String day, month, year;
        day = comboDay.getSelectedItem().toString();
        month = comboMonth.getSelectedItem().toString();
        year = comboYear.getSelectedItem().toString();
        String date = month +" "+ day +", "+ year;
        DateFormat format = new SimpleDateFormat("MMMM d, yyyy", Locale.ENGLISH);
        Date bDate = null;
        try {
            bDate = format.parse(date);
        } catch (ParseException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        java.sql.Date sqlDate = new java.sql.Date(bDate.getTime());
        return sqlDate;
    }

    public JRadioButton getRadioFemale() {
        return radioFemale;
    }

    public JRadioButton getRadioMale() {
        return radioMale;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignUp;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboDay;
    private javax.swing.JComboBox<String> comboMonth;
    private javax.swing.JComboBox<String> comboYear;
    private javax.swing.JTextField firstName;
    private javax.swing.JTextField lastName;
    private javax.swing.JLabel lblMotto;
    private javax.swing.JLabel lblPolicy;
    private javax.swing.JLabel lblSignUp;
    private javax.swing.JLabel lblTerms;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField mailField;
    private javax.swing.JPasswordField passwordLogin;
    private javax.swing.JPasswordField passwordSignUp;
    private javax.swing.JRadioButton radioFemale;
    private javax.swing.JRadioButton radioMale;
    private javax.swing.JTextField usernameLogin;
    private javax.swing.JTextField usernameSignUp;
    // End of variables declaration//GEN-END:variables

    @Override
    public void addListener(ActionListener e) {
        btnLogin.addActionListener(e);
        btnSignUp.addActionListener(e);
        
    }

}
